# Generated by Django 6.0.7 on 2026-07-20 09:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='nom')),
                ('color', models.CharField(default='#64748b', max_length=7, verbose_name='couleur')),
                ('icon', models.CharField(default='other', max_length=20, verbose_name='icone')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archivee')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'categorie',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('day', 'Journaliere'), ('week', 'Hebdomadaire'), ('month', 'Mensuelle'), ('year', 'Annuelle')], max_length=6, verbose_name='periode')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='montant')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='Laisser vide pour une limite globale, toutes categories confondues.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='budget.category', verbose_name='categorie')),
            ],
            options={
                'verbose_name': 'limite budgetaire',
                'verbose_name_plural': 'limites budgetaires',
                'ordering': ['period', 'category__name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='montant')),
                ('description', models.CharField(blank=True, max_length=140, verbose_name='description')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='date')),
                ('payment_method', models.CharField(choices=[('cash', 'Especes'), ('card', 'Carte bancaire'), ('mobile', 'Mobile money'), ('transfer', 'Virement'), ('check', 'Cheque'), ('other', 'Autre')], default='cash', max_length=10, verbose_name='mode de paiement')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='budget.category', verbose_name='categorie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'depense',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='FCFA', max_length=8, verbose_name='devise')),
                ('alert_threshold', models.PositiveSmallIntegerField(default=80, help_text="Pourcentage d'une limite a partir duquel une alerte est levee.", verbose_name="seuil d'alerte (%)")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('day', 'Jour'), ('week', 'Semaine'), ('month', 'Mois'), ('year', 'Annee')], max_length=6)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expense_count', models.PositiveIntegerField(default=0)),
                ('top_category', models.CharField(blank=True, max_length=60)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'rapport',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('warning', 'Seuil atteint'), ('exceeded', 'Limite depassee')], max_length=8)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('spent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('limit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('limit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='budget.budgetlimit')),
            ],
            options={
                'verbose_name': 'alerte',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('limit', 'level', 'period_start'), name='unique_alert_per_limit_period_level')],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_category_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='budgetlimit',
            constraint=models.UniqueConstraint(fields=('user', 'period', 'category'), name='unique_limit_per_period_and_category'),
        ),
        migrations.AddConstraint(
            model_name='budgetlimit',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', True)), fields=('user', 'period'), name='unique_global_limit_per_period'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', '-date'], name='budget_expe_user_id_7bcfbc_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'category', '-date'], name='budget_expe_user_id_4f3f49_idx'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('user', 'kind', 'period_start'), name='unique_report_per_period'),
        ),
    ]
