# Generated by Django 6.0.7 on 2026-07-20 11:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_reactiver_limites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='nom')),
                ('color', models.CharField(default='#0f766e', max_length=7, verbose_name='couleur')),
                ('icon', models.CharField(default='other', max_length=20, verbose_name='icone')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archivee')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'source de revenu',
                'verbose_name_plural': 'sources de revenus',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='montant')),
                ('description', models.CharField(blank=True, max_length=140, verbose_name='description')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='date')),
                ('method', models.CharField(choices=[('cash', 'Especes'), ('mobile', 'Mobile money'), ('transfer', 'Virement'), ('card', 'Carte bancaire'), ('check', 'Cheque'), ('other', 'Autre')], default='cash', max_length=10, verbose_name='mode de reception')),
                ('is_recurring', models.BooleanField(default=False, help_text='A cocher pour un revenu qui revient chaque periode (salaire, loyer...).', verbose_name='revenu recurrent')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='budget.incomesource', verbose_name='source')),
            ],
            options={
                'verbose_name': 'revenu',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='incomesource',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_source_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['user', '-date'], name='budget_inco_user_id_549df1_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['user', 'source', '-date'], name='budget_inco_user_id_66d454_idx'),
        ),
    ]
