# Generated by Django 6.0.7 on 2026-07-21 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_incomesource_income_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='kind',
            field=models.CharField(choices=[('limit', 'Limite budgetaire'), ('overspend', 'Depenses superieures aux revenus')], default='limit', max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='budget.budgetlimit'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'overspend')), fields=('user', 'period_start'), name='unique_overspend_per_month'),
        ),
    ]
