# Generated by Django 6.0.7 on 2026-08-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_alert_kind_alter_alert_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_backup',
            field=models.DateTimeField(blank=True, help_text='Horodatage du dernier export complet des donnees.', null=True, verbose_name='derniere sauvegarde'),
        ),
    ]
