# Generated by Django 6.0.7 on 2026-08-26 11:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_profile_last_backup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('expense', 'Depense'), ('income', 'Revenu')], max_length=8, verbose_name='type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='montant')),
                ('method', models.CharField(choices=[('cash', 'Especes'), ('card', 'Carte bancaire'), ('mobile', 'Mobile money'), ('transfer', 'Virement'), ('check', 'Cheque'), ('other', 'Autre')], default='cash', max_length=10, verbose_name='mode')),
                ('description', models.CharField(blank=True, max_length=140, verbose_name='description')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('frequency', models.CharField(choices=[('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('yearly', 'Annuel')], default='monthly', max_length=8, verbose_name='frequence')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='premiere echeance')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fin')),
                ('next_due', models.DateField(verbose_name='prochaine echeance')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('last_run', models.DateField(blank=True, null=True, verbose_name='derniere execution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurrences', to='budget.category', verbose_name='categorie')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurrences', to='budget.incomesource', verbose_name='source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'transaction recurrente',
                'verbose_name_plural': 'transactions recurrentes',
                'ordering': ['next_due'],
                'indexes': [models.Index(fields=['user', 'is_active', 'next_due'], name='budget_recu_user_id_f07379_idx')],
            },
        ),
    ]
