# Generated by Django 6.0.7 on 2026-08-28 10:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_recurringtransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nom')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='montant cible')),
                ('saved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='deja epargne')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='echeance')),
                ('color', models.CharField(default='#0f766e', max_length=9, verbose_name='couleur')),
                ('icon', models.CharField(default='saving', max_length=20, verbose_name='icone')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "objectif d'epargne",
                'verbose_name_plural': "objectifs d'epargne",
                'ordering': ['-created_at'],
            },
        ),
    ]
