# Generated by Django 6.0.7 on 2026-08-28 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_savingsgoal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsgoal',
            name='saved_amount',
        ),
        migrations.AddField(
            model_name='expense',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='budget.savingsgoal', verbose_name='objectif'),
        ),
    ]
