# Generated by Django 6.0.7 on 2026-09-02 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_remove_savingsgoal_saved_amount_expense_goal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onboarded',
            field=models.BooleanField(default=False, help_text="Vrai une fois l'assistant de premier lancement passe.", verbose_name='assistant termine'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='nom')),
                ('type', models.CharField(choices=[('cash', 'Especes'), ('mobile', 'Mobile money'), ('bank', 'Banque'), ('other', 'Autre')], default='cash', max_length=8, verbose_name='type')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='solde initial')),
                ('color', models.CharField(default='#0f766e', max_length=9, verbose_name='couleur')),
                ('icon', models.CharField(default='wallet', max_length=20, verbose_name='icone')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'compte',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='budget.account', verbose_name='compte'),
        ),
        migrations.AddField(
            model_name='income',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='budget.account', verbose_name='compte'),
        ),
    ]
