# Generated by Django 6.0.7 on 2026-09-07 10:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_profile_onboarded_account_expense_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('i_owe', 'Je dois'), ('owed_to_me', 'On me doit')], max_length=10, verbose_name='sens')),
                ('counterparty', models.CharField(max_length=80, verbose_name='crediteur / debiteur')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='montant')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='echeance')),
                ('note', models.TextField(blank=True, verbose_name='informations')),
                ('settled', models.BooleanField(default=False, verbose_name='soldee')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dette',
                'ordering': ['settled', 'due_date', '-created_at'],
            },
        ),
    ]
