# Generated by Django 6.0.7 on 2026-09-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tour_seen',
            field=models.BooleanField(default=False, help_text='Vrai une fois le tutoriel de decouverte passe.', verbose_name='tutoriel vu'),
        ),
    ]
